import { WarningProvider } from "@radix-ui/react-dialog"
import {
  Home,
  BarChart,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  Search,
  DollarSign,
  Users,
  Activity,
  Clock,
  Loader2,
  Plus,
  Check,
  ChevronsUpDown,
  FileText,
  Map,
  Edit,
  Trash,
  MoreHorizontal,
  Send,
  Eye,
  Download,
  CheckCircle,
  CircleX,
  ArrowLeft,
  Frown,
  ArrowRight,
  Upload,
  ArrowLeftCircle,
  List,
  Grid,
  File,
  Filter,
  Replace,
  Shield,
  Mail,
  UserX,
  UserCheck,
  Key,
  X,
  Briefcase,
  Heart,
  Baby,
  MessageSquare,
  Phone,
  MapPin,
  RefreshCw,
  AlertTriangle,
  ClipboardList,
  Archive,
  UserPlus,
  TrendingUp,
  HardHat,
  Calculator,
  Building2,
} from "lucide-react"

export const Icons = {
  home: Home,
  barChart: BarChart,
  settings: Settings,
  user: User,
  users: Users,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  search: Search,
  dollarSign: DollarSign,
  activity: Activity,
  clock: Clock,
  spinner: Loader2,
  plus: Plus,
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  fileText: FileText,
  map: Map,
  edit: Edit,
  trash: Trash,
  moreHorizontal: MoreHorizontal,
  send: Send,
  eye: Eye,
  download: Download,
  checkCircle: CheckCircle,
  circleX: CircleX,
  frown: Frown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  upload: Upload,
  arrowLeftCircle: ArrowLeftCircle,
  list: List,
  grid: Grid,
  plan: File,
  filter: Filter,
  replace: Replace,
  cancel: CircleX,
  file: File,
  admin: Shield,
  mail: Mail,
  userX: UserX,
  key: Key,
  close: X,
  x: X,
  briefcase: Briefcase,
  heart: Heart,
  baby: Baby,
  messageSquare: MessageSquare,
  phone: Phone,
  mapPin: MapPin,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
  clipboardList: ClipboardList,
  archive: Archive,
  userPlus: UserPlus,
  trendingUp: TrendingUp,
  userCheck: UserCheck,
  hardHat: HardHat,
  calculator: Calculator,
  building: Building2,
}

